language: node_js
node_js:
- '5'
before_script:
- npm install -g codeclimate-test-reporter
after_script:
- codeclimate-test-reporter < coverage/lcov.info
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: YVmd06Re+WMR6Ki1zJb1l7h5AYkv2Pcmash79PatkS9KpoLPzvF5N1UWBBoi1XEyxvgC+o2eWvzCeHQU/IsZRzgyyYcprVm0NB9twOLDLq3hlBSIdzB0updyjY2PA/mlrqQcKDpcvml3FiGNMrGSyE9ZVZq+B3v12qGEXvpxm2tCBAj2VnjkcTDjWCdh2Gr/XjB6Lha4ocKeAq+T98XRZC/vR9CcHMSOKgBRzNsQwBBKdFMSSDgQ9K708jIMum6pLIql3F0jTAo0GFzKpbt43kkpQkOLx68b0izqggG18Ew5qaaRisWxK2EhxIB/nZu2XlAhFrj5H8HwlAMuExoI8cuvB2/dSlvip3Q/2t5hDVhU+6/sxD6uIaUQAZjWYbkipnFNALkSMCaMw4jQVjS83a8FtW6hqsYCwmLy13pczL3lY1mWC13bZcb7qwctb8gwNcTjo4PGppVXK+W/qwoK3s/8prkUj5Kz299TsgSAj8uIxKFKGDtgHAEv0nd8SqwkqFjrLI5qQ4jM35Y+gfxsQrVX65PlxHPR79FP+gW6ALCgiGl4QDX91iSH+rK3nPQwnktSKvSRtG4QbbyO3z4FXyy2ZUxe9+XsWdt/+SifmlBqepiOOBBMnwVGshbDEg+a4QI5925v5IZ6FGpYORMIGWJM1XmGp3aV/GxSLSqK0EE=
  on:
    tags: true
    branches: true
